### ISSUE TITLE
opening controls.exe from GUI vs. mingw64 command line

### ISSUE THREAD

**Issue by andrewarrow** [dontpanic92/wxGo#12]
now that I can build windows wxGo projects I made the example controls project and can run the controls.exe from mingw64 command line like:

$ ./controls

and it works great! But when I double click on the exe from windows GUI it says:

"The program can't start because libstdc++-6.dll" is missing from your computer"

When I distribute my app to other windows users, how can I get error not to happen?

**Comment by dontpanic92** [comment]
The dll is in your mingw-w64 folder, typically `msys64/mingw64/bin`. It may also need other dlls, and they are all here.

**Comment by andrewarrow** [comment]
is there a way to compile them all in so I just distribute 1 exe file?

**Comment by dontpanic92** [comment]
Try adding `-static` in `#cgo LDFLAGS` in `setup_windows_amd64.go`

**Comment by andrewarrow** [comment]
worked!
