### ISSUE TITLE
missing wxTaskBarIcon::ShowBalloon

### ISSUE THREAD

**Issue by rakslice** [dontpanic92/wxGo#13]
wxGo is missing a wrapper for wxTaskBarIcon::ShowBalloon

https://github.com/wxWidgets/wxWidgets/blob/977a8266398a0851a13a640bce90d895d3756a43/src/msw/taskbar.cpp#L203

although it defines the associated event constants that can only be used with it (wxEVT_TASKBAR_BALLOON_TIMEOUT, wxEVT_TASKBAR_BALLOON_CLICK)

https://github.com/dontpanic92/wxGo/blob/master/src/wxGoInterface/taskbar.h

**Comment by rakslice** [comment]
I started out to work around this by doing the necessary Shell_NotifyIcon call from my own code, but got as far as figuring out that wxTaskBarIcon associates the NOTIFYICONDATA with a separate wxFrame wxTaskBarIconWindow with its own Hwnd which is inaccessible from the go side

**Comment by dontpanic92** [comment]
Confirmed.
I think in order to workaround this issue, we need some C++ code

**Comment by dontpanic92** [comment]
Should be fixed in the master branch. Please have a check.

**Comment by rakslice** [comment]
Tested, works great.
