### ISSUE TITLE
Program name cannot be changed from "wxGo" for standard menu items on Mac

### ISSUE THREAD

**Issue by rakslice** [dontpanic92/wxGo#14]
When running on Mac, the application name "wxGo" is shown in standard application menu items ("Quit wxGo", "Hide wxGo"). 

Speculating, it seems that this is based on the program name that is passed into wxEntryStart(), which is hardcoded to "wxGo" in src/wxApp.i, as that is the only place the string "wxGo" appears under src.  If so, it would be nice if wx.NewApp() could take the application name as a parameter, so that these menu items get names that will make sense to the user.

**Comment by dontpanic92** [comment]
Confirmed

**Comment by dontpanic92** [comment]
Fixed by #16
