### ISSUE TITLE
compiling on Mac with 10.12 but running on Macs with older os

### ISSUE THREAD

**Issue by andrewarrow** [dontpanic92/wxGo#15]
![screen shot 2016-12-19 at 12 12 43 pm](https://cloud.githubusercontent.com/assets/127054/21325081/61201fc6-c61c-11e6-8b06-4d5a7d09c1d1.png)

other than getting a Mac running os 10.11.6 and compiling the program there, is there a way to get my builds to run fine on older Macs?

**Comment by dontpanic92** [comment]
Try adding `-mmacosx-version-min=10.7` (10.7 is the minimum OS X version you want to support) option to `CPPFLAGS`

**Comment by dontpanic92** [comment]
Oh perhaps a rebuild of  wxWidgets is also needed....

**Comment by andrewarrow** [comment]
cool, I added `-mmacosx-version-min=10.7` to `github.com/dontpanic92/wxGo/wx/setup_darwin.go` took a long time to compile but worked and produced a binary slightly larger than the one without that flag. I assume that means it's going work on older Macs now. But I don't have an older Mac to test with. Closing for now :)
