### ISSUE TITLE
Go get (building) on linux_amd64 

### ISSUE THREAD

**Issue by ernierasta** [dontpanic92/wxGo#18]
Hi,
i have problem compiling/installing wxGo on 64-bit linux (tested on: debian 8 with gcc 6.3.0 from unstable and 64-bit alpine linux muslc lib based). There are many messages such as:

> relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC

and at the end I got:

> /usr/bin/ld: final link failed: Nonrepresentable section on output
> collect2: error: ld returned 1 exit status

Do you have any idea if this can be fixed?

Here is full output: [compilation error](https://gist.github.com/ernierasta/4ceff51d59812faab3e18853189c66eb).

**Comment by dontpanic92** [comment]
I can reproduced the errors on debian 8.7 with gcc 6.3.0. It seems that the errors are caused by the libs not compiled with -fPIC opiton.

It is so weird that gcc 6.3.1 on Arch Linux and gcc 5.4.1 on Ubuntu work fine. I will recompile these libs asap.

**Comment by ernierasta** [comment]
Great, just out of curiosity i tried it on ubuntu 16.10 with default gcc 6.2.0 - the same problem, hopefully recompiling with -fPIC will solve it. I am ready to make tests with recompiled libs.

**Comment by dontpanic92** [comment]
I have updated these libs and please have a try.

By the way, gtk2 backend of wxWidgets is also added and can be used with `-tags gtk2`, i.e.
`go install -tags gtk2 -x github.com/dontpanic92/wxGo/wx`

**Comment by ernierasta** [comment]
Hi!
I successfully buid it on actual Debian 8 with gcc 6.3.0 (from testing this time) and Ubuntu 16.10.

This problem is solved. Thank you!

BTW: Can you please mention possibility of using gtk2 backend in the readme? It can be helpful for everyone.

I would like to contribute installation instructions for Debian and Ubuntu to the wiki. Can you put there something like this? Feel free to modify as you want.

Debian:
https://gist.github.com/ernierasta/d6f40e69543ebb5274967f19a3cd649d

Ubuntu:
https://gist.github.com/ernierasta/1e4acf4a4190dd7eaf2deed4151438d9

**Comment by dontpanic92** [comment]
> BTW: Can you please mention possibility of using gtk2 backend in the readme? It can be helpful for everyone.

Of course, and thank you for your installation guide!
