### ISSUE TITLE
How to get in Windows OS?

### ISSUE THREAD

**Issue by arafath-mk** [dontpanic92/wxGo#2]
I used following command in Windows 10.
`go get github.com/dontpanic92/wxGo/wx`

But showed following error.
`package github.com/dontpanic92/wxGo/wx: no buildable Go source files in D:\Projects\GoUI\src\github.com\dontpanic92\wxGo\wx`

**Comment by dontpanic92** [comment]
So sorry but right now I haven't added any Windows support, and even on linux it isn't fully tested and full-featured.

I will make it work on Windows as soon as possible, but it may still have some bugs or lack some features. If you find anything buggy, please let me know :smile:

**Comment by arafath-mk** [comment]
Thanks. Please make the wxGo to be capable for cross platform support.

**Comment by dontpanic92** [comment]
@arafath-mk Hi, you can have a try now in Windows, but only 64bit go can compile because 32bit go compiler will run out of memory when compiling.

And you also need mingw installed. tdm-gcc is recommended as it statically links libgcc. mingw-w64 should work too.

**Comment by arafath-mk** [comment]
Thanks.. Nice Work..!

**Comment by cgimenez** [comment]
Hi, same answer about a max osx support...
With a modified Makefile I can go through the SWIG phase
But go install stops at
In file included from wx/wx_wrap_osx.cxx:240:
In file included from wx/../wxWidgets/wxWidgets-3.1.0/include/wx/wx.h:14:
In file included from wx/../wxWidgets/wxWidgets-3.1.0/include/wx/defs.h:20:
wx/../wxWidgets/wxWidgets-3.1.0/include/wx/platform.h:136:10: fatal error: 'wx/setup.h' file not found

**Comment by dontpanic92** [comment]
Hi @cgimenez , the `setup.h` file is generated during wxWidgets' compilation, and you can find it in the `lib/` directory.

**Comment by cgimenez** [comment]
I downloaded and compiled the 3.1.0 version in a separate directory, everything went fine... But from now I don't know what to do next. I presume that I have to copy some files from the compiled directory to the go package directory, but which ones ? wxWidgets tree is a big beast with many many files...

Thanks for you help ! I'm coding an app that will need a pretty having UI and having wxwidgets bindings for Go on macosx would save my summer ;-)

**Comment by cgimenez** [comment]
I just tried something : I replaced the pkg wxWidgets-3.1.0 with the compiled one and copied include/wx/osx/setup.h to include/wx

Now I got a bunch of errors when doing go install -v -x github.com/dontpanic92/wxGo/wx

`
In file included from ./wx_wrap_osx.cxx:240:
In file included from ./../wxWidgets/wxWidgets-3.1.0/include/wx/wx.h:14:
In file included from ./../wxWidgets/wxWidgets-3.1.0/include/wx/defs.h:20:
In file included from ./../wxWidgets/wxWidgets-3.1.0/include/wx/platform.h:485:
In file included from ./../wxWidgets/wxWidgets-3.1.0/include/wx/chkconf.h:1267:
./../wxWidgets/wxWidgets-3.1.0/include/wx/unix/chkconf.h:26:13: error: "wxFileSystemWatcher requires either inotify() or kqueue()"
In file included from ./wx_wrap_osx.cxx:240:
In file included from ./../wxWidgets/wxWidgets-3.1.0/include/wx/wx.h:14:
./../wxWidgets/wxWidgets-3.1.0/include/wx/defs.h:1059:53: error: named bit-field 'SizeTMustBeExactly4Bytes' has zero width
./../wxWidgets/wxWidgets-3.1.0/include/wx/debug.h:442:57: note: expanded from macro 'wxCOMPILE_TIME_ASSERT'
In file included from ./wx_wrap_osx.cxx:240:
In file included from ./../wxWidgets/wxWidgets-3.1.0/include/wx/wx.h:14:
./../wxWidgets/wxWidgets-3.1.0/include/wx/defs.h:1060:53: error: named bit-field 'PtrMustBeExactly4Bytes' has zero width
./../wxWidgets/wxWidgets-3.1.0/include/wx/debug.h:442:57: note: expanded from macro 'wxCOMPILE_TIME_ASSERT'
In file included from ./wx_wrap_osx.cxx:240:
In file included from ./../wxWidgets/wxWidgets-3.1.0/include/wx/wx.h:14:
./../wxWidgets/wxWidgets-3.1.0/include/wx/defs.h:1063:17: warning: 'SIZEOF_SIZE_T' macro redefined [-Wmacro-redefined]
./../wxWidgets/wxWidgets-3.1.0/include/wx/platform.h:390:17: note: previous definition is here
In file included from ./wx_wrap_osx.cxx:240:
In file included from ./../wxWidgets/wxWidgets-3.1.0/include/wx/wx.h:14:
./../wxWidgets/wxWidgets-3.1.0/include/wx/defs.h:1064:17: warning: 'SIZEOF_VOID_P' macro redefined [-Wmacro-redefined]
./../wxWidgets/wxWidgets-3.1.0/include/wx/platform.h:388:17: note: previous definition is here
In file included from ./wx_wrap_osx.cxx:240:
In file included from ./../wxWidgets/wxWidgets-3.1.0/include/wx/wx.h:14:
./../wxWidgets/wxWidgets-3.1.0/include/wx/defs.h:1241:25: error: typedef redefinition with different types ('wxInt32' (aka 'int') vs '__darwin_ssize_t' (aka 'long'))
/usr/include/sys/_types/_ssize_t.h:30:33: note: previous definition is here
In file included from ./wx_wrap_osx.cxx:240:
In file included from ./../wxWidgets/wxWidgets-3.1.0/include/wx/wx.h:30:
In file included from ./../wxWidgets/wxWidgets-3.1.0/include/wx/stopwatch.h:21:
./../wxWidgets/wxWidgets-3.1.0/include/wx/time.h:62:2: warning: using pseudo thread-safe wrapper for localtime to emulate localtime_r [-W#warnings]
./../wxWidgets/wxWidgets-3.1.0/include/wx/time.h:72:2: warning: using pseudo thread-safe wrapper for gmtime to emulate gmtime_r [-W#warnings]
./wx_wrap_osx.cxx:29524:11: error: no member named 'SetDoubleBuffered' in 'wxWindow'
./wx_wrap_osx.cxx:31852:28: error: no matching constructor for initialization of 'wxCursor'
./../wxWidgets/wxWidgets-3.1.0/include/wx/gtk1/cursor.h:26:5: note: candidate constructor not viable: requires single argument 'id', but 2 arguments were provided
./../wxWidgets/wxWidgets-3.1.0/include/wx/gtk1/cursor.h:31:5: note: candidate constructor not viable: requires single argument 'image', but 2 arguments were provided
./../wxWidgets/wxWidgets-3.1.0/include/wx/gtk1/cursor.h:22:24: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
./../wxWidgets/wxWidgets-3.1.0/include/wx/gtk1/cursor.h:25:5: note: candidate constructor not viable: requires 0 arguments, but 2 were provided
./../wxWidgets/wxWidgets-3.1.0/include/wx/gtk1/cursor.h:33:5: note: candidate constructor not viable: requires at least 3 arguments, but 2 were provided
./wx_wrap_osx.cxx:38363:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
./wx_wrap_osx.cxx:42702:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
./wx_wrap_osx.cxx:48156:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
./wx_wrap_osx.cxx:54269:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
./wx_wrap_osx.cxx:76612:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
./wx_wrap_osx.cxx:82269:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
./wx_wrap_osx.cxx:87100:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
./wx_wrap_osx.cxx:94475:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
./wx_wrap_osx.cxx:100576:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
./wx_wrap_osx.cxx:110577:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
./wx_wrap_osx.cxx:117560:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
./wx_wrap_osx.cxx:124830:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
./wx_wrap_osx.cxx:128913:11: error: too many arguments to function call, expected 0, have 1; did you mean 'wxTextAreaBase::SetModified'?
./../wxWidgets/wxWidgets-3.1.0/include/wx/textctrl.h:557:10: note: 'wxTextAreaBase::SetModified' declared here
fatal error: too many errors emitted, stopping now [-ferror-limit=]
`

**Comment by dontpanic92** [comment]
Hi, I'm not sure about all the errors, but for the `SetDoubleBuffered` error I found that in osx the `wxWindow` doesn't have the member `SetDoubleBuffered`, which is not documented. You can have a look at `wxWidgets-3.1.0/include/wx/gtk/window.h`, they say that this function is only available in gtk2. However in `wx/msw/window.h` I also found it, but not in `wx/osx/window.h`.

To solve this problem, you need to edit `wxGo/src/wxGoInterface_original/window.h`, surround `SetDoubleBuffered` with `#ifndef __WXMAC__`.

The other errors are weird. Something in `gtk1/` is included which should not be.

**Comment by cgimenez** [comment]
Hi Li, I tried with the #ifndef directive...Didn't worked

The wxwidgets demos compiles fine. So as a blind shoot I copy/pasted some c++ flags to the setup_darwin_amd64.go (copied from setup_linux) with
`package wx
// #cgo CPPFLAGS: -DWX_PRECOMP -O2 -fno-common
// #cgo CPPFLAGS: -I${SRCDIR}/darwin_amd64/ -I${SRCDIR}/../wxWidgets/wxWidgets-3.1.0/include -D_FILE_OFFSET_BITS=64 -D__WXOSX_COCOA__
// #cgo CXXFLAGS: -I${SRCDIR}/../wxWidgets/wxWidgets-3.1.0/include -D_FILE_OFFSET_BITS=64 -D__WXOSX_COCOA__
// #cgo LDFLAGS: -L${SRCDIR}/darwin_amd64/lib -pthread  -lwx_gtk2u_xrc-3.1 -lwx_gtk2u_webview-3.1 -lwx_gtk2u_stc-3.1 -lwx_gtk2u_richtext-3.1 -lwx_gtk2u_ribbon-3.1 -lwx_gtk2u_propgrid-3.1 -lwx_gtk2u_aui-3.1 -lwx_gtk2u_gl-3.1 -lwx_gtk2u_qa-3.1 -lwx_baseu_net-3.1 -lwx_gtk2u_html-3.1 -lwx_gtk2u_adv-3.1 -lwx_gtk2u_core-3.1 -lwx_baseu_xml-3.1 -lwx_baseu-3.1 -lwxscintilla-3.1 -lGL -lGLU -lgthread-2.0 -pthread -lX11 -lXxf86vm -lSM -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lpangoft2-1.0 -lpango-1.0 -lfontconfig -lfreetype -lnotify -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lpng -ljpeg -ltiff -lexpat -lwxregexu-3.1 -lz -ldl -lm 
// #cgo LDFLAGS: -s
import "C"
`

Some compilation errors seems to be gone but SetDoubleBuffer still making problems (once again I tried the #ifndef directive)...
`
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:29524:11: error: no member named 'SetDoubleBuffered' in 'wxWindow'
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:31735:28: error: no matching constructor for initialization of 'wxCursor'
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:23:5: note: candidate constructor not viable: requires at most 4 arguments, but 6 were provided
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:22:5: note: candidate constructor not viable: requires single argument 'image', but 6 arguments were provided
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:27:5: note: candidate constructor not viable: requires single argument 'id', but 6 arguments were provided
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:17:24: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 6 were provided
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:20:5: note: candidate constructor not viable: requires 0 arguments, but 6 were provided
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:31756:28: error: no matching constructor for initialization of 'wxCursor'
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:23:5: note: candidate constructor not viable: requires at most 4 arguments, but 5 were provided
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:22:5: note: candidate constructor not viable: requires single argument 'image', but 5 arguments were provided
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:27:5: note: candidate constructor not viable: requires single argument 'id', but 5 arguments were provided
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:17:24: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 5 were provided
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:20:5: note: candidate constructor not viable: requires 0 arguments, but 5 were provided
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:31775:28: error: no matching constructor for initialization of 'wxCursor'
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:23:5: note: candidate constructor not viable: no known conversion from 'int' to 'wxBitmapType' for 2nd argument
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:22:5: note: candidate constructor not viable: requires single argument 'image', but 4 arguments were provided
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:27:5: note: candidate constructor not viable: requires single argument 'id', but 4 arguments were provided
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:17:24: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 4 were provided
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:20:5: note: candidate constructor not viable: requires 0 arguments, but 4 were provided
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:31792:28: error: no matching constructor for initialization of 'wxCursor'
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:23:5: note: candidate constructor not viable: no known conversion from 'int' to 'wxBitmapType' for 2nd argument
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:22:5: note: candidate constructor not viable: requires single argument 'image', but 3 arguments were provided
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:27:5: note: candidate constructor not viable: requires single argument 'id', but 3 arguments were provided
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:17:24: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 3 were provided
../github.com/dontpanic92/wxGo/wx/../wxWidgets/wxWidgets-3.1.0/include/wx/osx/cursor.h:20:5: note: candidate constructor not viable: requires 0 arguments, but 3 were provided
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:38363:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:42702:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:48156:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:54269:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:76612:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:82269:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:87100:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:94475:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:100576:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:110577:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:117560:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:124830:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:132903:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
../github.com/dontpanic92/wxGo/wx/wx_wrap_osx.cxx:138716:14: error: no member named 'SetDoubleBuffered' in 'wxWindow'
fatal error: too many errors emitted, stopping now [-ferror-limit=]`

**Comment by dontpanic92** [comment]
@cgimenez You also have to add the macro using `-D` option of SWIG. For example, in the `linux` section of `build/Makefile`, it uses the `-D__WXGTK__` option to define the `__WXGTK__` macro.

`

**Comment by dontpanic92** [comment]
@cgimenez By the way, does wxWidgets in OSX use gtk? I saw that you add some gtk lib in `setup.go`.

**Comment by dontpanic92** [comment]
OS X support added

**Comment by dtrehas** [comment]
What if you try to cross compile 32-bit wxWidgets with 64-bit Go Compiler ( GOARCH=386)  having also 32-bit gcc compiler?

 package github.com/dontpanic92/wxGo/wx: no buildable Go source files in C:\Programming\GOPATH\src\github.com\dontpanic92\wxGo\wx

**Comment by dontpanic92** [comment]
@dtrehas You also have to manually set CGO_ENABLED = 1. When cross compiling, go compiler will disable cgo by default.

**Comment by dtrehas** [comment]
Thank you for your work and your advice. Much appreciated. Before I get involved with your project in windows, do you think OLE (ActiveX) can be used in Windows with Golang? I saw them in .h files

**Comment by dontpanic92** [comment]
I don't have much knowledge about OLE, but I think it can be used in Golang as they are just normal C++ classes, as long as we deal with the reference counting correctly.
