### ISSUE TITLE
Errors in the execution of the "go get ..." command

### ISSUE THREAD

**Issue by adva-cg** [dontpanic92/wxGo#20]
I'm a beginner both in go, and in wxWidgets and even in English and in linux. Please excuse me if I make a mistake.

After executing the command on linux_amd64 (lubuntu) issued errors:
[logGoGet.txt](https://github.com/dontpanic92/wxGo/files/870122/logGoGet.txt)

What should I install in advance?

**Comment by dontpanic92** [comment]
If you are using Ubuntu or it's derivatives, please install 

- libxxf86vm-dev
 - libnotify-dev
 - libgtk-3-dev
- libpango1.0-dev
- libatk1.0-dev
- libglib2.0-dev
- libglib2.0-0
 - libglu1-mesa-dev
 - libjpeg-dev
- libtiff-dev
- libgstreamer1.0-dev
 - libgstreamer-plugins-base1.0-dev
 - libwebkitgtk-3.0-dev

with the following command
`sudo apt-get install libxxf86vm-dev libnotify-dev libgtk-3-dev libpango1.0-dev libatk1.0-dev libglib2.0-dev libglib2.0-0 libglu1-mesa-dev  libjpeg-dev libtiff-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libwebkitgtk-3.0-dev`

If you are using other distribution, you can have a search about the equivalent packages that your distribution offers.

**Comment by adva-cg** [comment]
Thank you. I'll try this.

**Comment by adva-cg** [comment]
Previous error fixed, but not enough memory to complete compilation (only 3.5Gb). Still I'll try to compile on win10. If it does not help, I'll wait binary-only packages or look for other solution.

**Comment by dontpanic92** [comment]
If it cannot compile on ubuntu, I don't think it will compile on win10 either.

**Comment by adva-cg** [comment]
Ubuntu is on VirtualBox, I couldn't allocate >5 GB of memory. I tried to use Swap, but I couldn't wait for the compilition to finish. On win10 is 6Gb RAM. All was compiled fast enough. I will begin to study Golang and wxWidgets. Thank you for your work
