### ISSUE TITLE
Document/View Framework

### ISSUE THREAD

**Issue by adva-cg** [dontpanic92/wxGo#21]
Hi,

Is wxGo support Document/View Framework? http://docs.wxwidgets.org/3.0/overview_docview.html#overview_docview_wxdoc

Unfortunately I could not understand the examples on C++. Is there an example on Golang?

**Comment by adva-cg** [comment]
Unlike "wx.NewFrame" "wx.NewDocParentFrame" gives an error - "undefined".

**Comment by dontpanic92** [comment]
Hi, the document/view related classes are not wrapped yet. I will add them as soon as possible

**Comment by adva-cg** [comment]
Thank you, I'll wait

**Comment by dontpanic92** [comment]
Finally make it work. To use the doc/view framework, an inheritance mechanism is needed.

I have also made a doc/view example, a simplified version of the docview example in wxWidgets.
