### ISSUE TITLE
Pre-compiled release for Go 1.8.3

### ISSUE THREAD

**Issue by PaluMacil** [dontpanic92/wxGo#26]
After having trouble with the main branch, I tried downloading a release, but it targets 1.8, and I've already updated to the latest patch release. Could you release a version for 1.8.3 please?

**Comment by dontpanic92** [comment]
OK, I will release it as soon as possible.

**Comment by PaluMacil** [comment]
Thanks :)

**Comment by dontpanic92** [comment]
Precompiled packages for windows have been uploaded. Please have a try.

**Comment by PaluMacil** [comment]
Tested, working, great!

(still wishing I could get compile to work in my other issue, but I'll close this one)

Thanks!
