### ISSUE TITLE
How to use DataViewCtrl? 

### ISSUE THREAD

**Issue by any626** [dontpanic92/wxGo#28]
Hello,
I'm new to wxwidet and gui's. I'm trying to build a dataviewctrl but i'm running into some errors.

```
dataViewCtrl := wx.NewDataViewCtrl(self, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, 5, wx.DefaultValidator)
dataViewCtrl.AppendToggleColumn("toggle")
dataViewCtrl.AppendTextColumn("text")

```
But I end up getting the follow error:

panic: No match for overloaded function call

goroutine 1 [running]:
github.com/dontpanic92/wxGo/wx.SwigClassDataViewCtrl.AppendTextColumn(0x63599c0, 0x63599c0, 0x63599c0, 0x63599c0, 0x63599c0, 0x63599d0, 0xc420011130, 0x1, 0x1, 0xc42004fd90, ...)
...

If anyone could help me out that would be great!

**Comment by dontpanic92** [comment]
According to the [wx document](http://docs.wxwidgets.org/3.1/classwx_data_view_ctrl.html#a98a01c0dcc31d2f907c181bd82e0317f), the `AppendTextColumn` receives at least 2 parameters. So you have to specify the second `unsigned int model_column`.

**Comment by any626** [comment]
Wow, overlooked that detail.
Thanks for the help! Love the library!
