### ISSUE TITLE
Code prompt unavailable in Gogland.

### ISSUE THREAD

**Issue by rafw** [dontpanic92/wxGo#36]
Compile sucess, but can't use code prompt function of Gogland.

<img width="609" alt="2017-10-18 1 27 57" src="https://user-images.githubusercontent.com/4507840/31702244-39c00c80-b39b-11e7-8ddc-bde095568d51.png">

**Comment by jakecoffman** [comment]
I think this is due to wx_*.go files being so large. This is what I see when I open one of those files: 

<img width="611" alt="screen shot 2017-10-18 at 7 01 35 pm" src="https://user-images.githubusercontent.com/886768/31748170-e0cce930-b436-11e7-9b10-133ae94eae43.png">

**Comment by rafw** [comment]
Step I:
gogland.vmoptions -> `idea.max.intellisense.filesize=2500` -> change `2500`  to `25000`

Step II:
idea.properties -> change `-Xmx750m` to `-Xmx1500m`

Maybe there is better configure method in GUI settings!
