### ISSUE TITLE
How do I capture a panic backtrace?

### ISSUE THREAD

**Issue by axelniedenhoff** [dontpanic92/wxGo#42]
I am probably missing something very obvious here…
I have a wxGo application under Windows that simply vanishes at some point. I suspect that there is a panic somewhere, but I cannot see it. How can I capture the panic backtrace? (I saw in another issue here that this is apparently possible.)

**Comment by dontpanic92** [comment]
I personally use the bash shell in MSYS2 which can get the error output by default.
If you are using PowerShell, try `.\test2.exe 2>&1 | echo`

**Comment by axelniedenhoff** [comment]
I have checked the PowerShell approach. It works like a charm. Thank you!
