### ISSUE TITLE
Failed to convert wx.Event to wx.MouseEvent in wx.EVT_LEFT_DCLICK

### ISSUE THREAD

**Issue by xinhuang** [dontpanic92/wxGo#46]
I have following code snippet to handle double clicks:

```
wx.Bind(panel, wx.EVT_LEFT_DCLICK, func(e wx.Event) {
    mouseEvt := wx.MouseEvent(e)
    // ...
}
```

But the compiler complains about the conversion:
```
./main.go:12:28: cannot convert e (type wx.Event) to type wx.MouseEvent:
	wx.Event does not implement wx.MouseEvent (missing AltDown method)
```

I checked `wxGo/src/wxGoInterface/event.h` but didn't find `AltDown` method in `wx.MouseEvent`. Is there anything I did wrong?

Thanks!

**Comment by dontpanic92** [comment]
Please try to use `wx.ToMouseEvent(e)`. This is something like `reinterpret_cast<wxMouseEvent>` in C++. Types are erased during callback.

BTW, In Go, it is invalid to use "type conversion" to convert an base interface into a concrete interface. Instead, you should use "[type assertion](https://golang.org/ref/spec#Type_assertions)": `x.(T)`.

**Comment by xinhuang** [comment]
Oh sorry. That's a silly mistake. The C++ part of my brain just jumped in to my go program. :P
