### ISSUE TITLE
strange output file on windows

### ISSUE THREAD

**Issue by ismlsmile** [dontpanic92/wxGo#5]
Thanks for your job, it is a great project! I think go and wxwidgets is an excellent combination. But I meet some problem when using it. I am testing on Windows 7 ( go 1.7, tdm64-gcc-5.1.0-2), and I install wxGo using the following command:

go get github.com/dontpanic92/wxGo/wx

the installtion meets some warnings but no errors, and then I try the example "control":
I change the cmd current directory to "control" and run
go build

after a long time, the exe file is created. It is 60M, very large, and when I run it, It do open a window, but the ui is very strage, some text like "existsfloat32nan2float64nan1...", I upload a picture here. Where is the problem?
![demo](https://cloud.githubusercontent.com/assets/1876179/18157776/fbfb5216-7051-11e6-90fc-afbc7f634da8.png)

**Comment by ismlsmile** [comment]
I test on linux(Fedora 24, golang 1.7), it has the same problem

![test](https://cloud.githubusercontent.com/assets/1876179/18160463/34562cd6-7060-11e6-99c5-e870e98d49b1.png)

**Comment by ismlsmile** [comment]
I tried with go 1.6, it works well. It seems that the problem is with go 1.7.   go 1.7 has done some job in order to reduce the output file size, could be this the reason?

**Comment by dontpanic92** [comment]
Hi ismlsmile,

Thanks for your feedback. 

> after a long time, the exe file is created. It is 60M, very large

The filesize is indeed unfriendly. In Linux, I could use `-s` option of gcc to strip the useless symbols in the wrapper layer, where there are many auto-generated functions. However, in Windows the linker (i.e ld.exe) will exit abnormally when I use `-s` option, and `strip.exe` doesn't work neither. You can find that in Linux the filesize is much smaller.

> I tried with go 1.6, it works well. It seems that the problem is with go 1.7. go 1.7 has done some job in order to reduce the output file size, could be this the reason?

Maybe, It looks like the strings get corrupted. I have to check the changes in go 1.7.

**Comment by dontpanic92** [comment]
@ismlsmile Hi, the problem is caused by a bug in wxGo. It should be solved now.

**Comment by dontpanic92** [comment]
Nope. I compile wxWidgets as it, but wxGo needs wxWidgets' interface headers, which you can find in the `src/wxGoInterface_original` folder. They are slightly modified, for example they are added some macro in order to support different platforms.
