### ISSUE TITLE
Embedding images

### ISSUE THREAD

**Issue by blimmo** [dontpanic92/wxGo#50]
In wxWidgets in C, I've used the `wxBITMAP_PNG_FROM_DATA` macro along with `xpm` files. Obviously this doesn't work in go so can anyone recommend an approach that does? 

I'd like to keep the images embedded in the executable and not separate. Also I'd prefer something cross platform (why I liked xpm so much).

**Comment by dontpanic92** [comment]
Indeed xpm is not working now, as the `char*` doesn't correctly mapped when it is used for binary data rather than a string. I will take a look at that

**Comment by dontpanic92** [comment]
The mapping is updated. Now we can use a string slice to construct a `wxImage` or `wxBitmap`. Please have a check on`examples/webview` for usage reference

**Comment by blimmo** [comment]
Thanks that's great!

On another note I'd like to use something like the [`wx.Bitmap.NewFromPNGData`](http://docs.wxwidgets.org/3.0/classwx_bitmap.html#a2048897970d5e845040fcfc0259e1be1) method to display images from raw data (I have it in a `[]byte`).

The equivalent function in wxGo is `wx.BitmapNewFromPNGData` but this takes a `uintptr` so I'm not sure if this is wrapped properly?

Thanks again for the quick response on xpm :)

**Comment by dontpanic92** [comment]
Updated, please check the webview example about the `NewFromPNGData`

**Comment by blimmo** [comment]
Damn you're quick!

I notice you haven't freed the bitmap you've created in the example. Is this intentional and `Bitmap` is memory managed or should I be calling `wx.DeleteBitmap`?

**Comment by dontpanic92** [comment]
Oh that is a mistake :(, and `wx.DeleteBitmap` should be called. It seems that `image` should also be deleted. I'll fix them

**Comment by blimmo** [comment]
Actually could you add a T version which is managed by go like `wx.NewBitmapT`? I often use it in a `wx.NewStaticBitmap` and it would be nice to be able to use it inline.

**Comment by dontpanic92** [comment]
My apologize - I was wrong in the previous reply - they are already tracked by Go. What these functions returns are `wxBitmap` and `wxImage`(instead of a `wxBitmap*` and `wxImage*`).

**Comment by blimmo** [comment]
Oh great!

Thanks for all your help on this :)
