### ISSUE TITLE
Closed Source Usage

### ISSUE THREAD

**Issue by philiplb** [dontpanic92/wxGo#53]
Hi,
assuming I want to write aclosed source program and publich it using this library.
Am I allowed to do so license wise? Especially with the license of wxWidgets?

**Comment by dontpanic92** [comment]
In my understanding, Yes. The license that wxWidgets uses is a modified version of LGPL - the modification is that you are allowed to distribute the binary when linked as a static lib (even when you modified it).

> 2. The exception is that you may use, copy, link, modify and distribute
under your own terms, binary object code versions of works based on the
Library.

**Comment by philiplb** [comment]
Thank you very much for the answer and of course this lib. :-)
