### ISSUE TITLE
Goland: Getting autocompletion

### ISSUE THREAD

**Issue by philiplb** [dontpanic92/wxGo#55]
Hi,
currently, there is no auto completion with this library in Goland. I assume it's because of the C-Code?
Example:
<img width="308" alt="screen shot 2018-04-01 at 15 48 34" src="https://user-images.githubusercontent.com/1672238/38173811-2d8ea1d2-35c4-11e8-9630-90f9aa1031d8.png">

**Comment by dontpanic92** [comment]
It is supposed to work. Please have a check on this #36

**Comment by philiplb** [comment]
Changing those settings worked well, all good now. Thank you! :)
