### ISSUE TITLE
Can't Printf in a Bind.

### ISSUE THREAD

**Issue by undeadindustries** [dontpanic92/wxGo#60]
Why debugging, I can't see any Println or Printf in the console. In in Win10 x64.

wx.Bind(w, wx.EVT_BUTTON, func(e wx.Event) {
		fd := wx.NewDirDialog(wx.NullWindow, "Select Folder")
		if fd.ShowModal() == wx.ID_OK {
			fmt.Printf("Folder: %v", fd.GetPath())
		}
		fmt.Println("Whatever")
	},

This doesn't display anything on the console. 

Any ideas?

**Comment by dontpanic92** [comment]
Try :
- Attach a console using `AttachConsole`
- Redirect the stdout/stderr using `freopen`

**Comment by undeadindustries** [comment]
Thanks that worked!
