### ISSUE TITLE
SetVeto in EVT_CLOSE_WINDOW?

### ISSUE THREAD

**Issue by undeadindustries** [dontpanic92/wxGo#65]
How would I set veto in a Bind?

```
wx.Bind(w, wx.EVT_CLOSE_WINDOW, func(e wx.Event) {
		e.SetVeto(false) //????
	}, w.GetId())
```

Thanks!

**Comment by Asday** [comment]
I believe you're after `.Veto()`, defined [here](https://github.com/dontpanic92/wxGo/blob/2190c22bde3f6d1751bf07dcb9876dc25e3580fc/src/wxGoInterface_original/event.h#L544).

**Comment by undeadindustries** [comment]
I tried that before I posted here. It doesn't seem to think Veto is part of "e" ... 

If you copy and my paste that code into a quick app, to see if it does it for you?

Wish I could post an image of it here.

Thank you!

**Comment by Asday** [comment]
![screenshot_20180817-205443](https://user-images.githubusercontent.com/340276/44286124-e311fd80-a25f-11e8-9315-ac50788a22d9.jpg)

This is what I'm going off.  That, and the official `wx` docs list `.Veto()` as the function to use on [`wxCloseEvent`](http://docs.wxwidgets.org/3.1/classwx_close_event.html#a0ec337c77613d5d8407831cd64e16417).

If you could put together a small repository demonstrating your issue, I'll check it out when I wake up.  At least then I'll be able to see the error codes.

**Comment by dontpanic92** [comment]
I think firstly, you should convert the event to `CloseEvent`. 
```
closeEvent := wx.ToCloseEvent(e)
```

`CloseEvent` has a method named `Veto`.

```
closeEvent.Veto()
```

**Comment by undeadindustries** [comment]
Hi there. I tried
closeEvent := wx.ToCloseEvent(e)

Now it's telling me: Call To Veot() ignored. Can't veto this event.

**Comment by undeadindustries** [comment]
dontpanic92, that worked!

However, when I have something bound to my close event, the window doesn't close. I'll update this soon if I don't sort it out. If not, I'll close this. Thank you!

**Comment by undeadindustries** [comment]
I forgot to add Destroy() at the end. all set. Thanks again!!
